package:
  name: qemu
  version: 7.0.0

source:
  url: https://download.qemu.org/qemu-7.0.0.tar.xz
  sha256: f6b375c7951f728402798b0baabb2d86478ca53d44cedbefabbe1c46bf46f839

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtool
    - make
    - meson >=0.62
    - ninja
    - pkg-config
    - sphinx
    - sphinx_rtd_theme >=0.4
  host:
    - bzip2
    - gettext
    - glib
    - jpeg
    - libffi
    - libpng
    - libslirp
    - lzo
    - pixman
    - snappy
    - zlib
  run:
    - bzip2
    - gettext
    - glib
    - jpeg
    - libffi
    - libpng
    - libslirp
    - lzo
    - pixman
    - snappy
    - zlib

test:
  commands:
    - test -f ${PREFIX}/bin/qemu-system-x86_64
    - test -f ${PREFIX}/bin/qemu-img
    - test -d ${PREFIX}/share/qemu/

about:
  home: https://www.qemu.org/
  dev_url: https://gitlab.com/qemu-project/qemu
  license: GPL-2
  license_file: LICENSE
  summary: QEMU is a generic and open source machine & userspace emulator and virtualizer.

