{% set version = "4.7.0" %}

package:
  name: libslirp
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/slirp/libslirp/uploads/60113f60cfd6abe2c16dde9f6c81b631/libslirp-{{ version }}.tar.xz
  sha256: 355aa2fbbaf6232135d7973fdbbbc85da22ea3f6a57f41164eeaa9e05d8a4f7e

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - meson >=0.50
    - ninja
    - pkg-config
  host:
    - glib
  # - libglib in the conda-forge recipe just duplicates a subset of glib
  run:

test:
  commands:
    - test -f ${PREFIX}/include/slirp/libslirp.h
    - test -f ${PREFIX}/lib/libslirp${SHLIB_EXT}
    - test -f ${PREFIX}/lib/pkgconfig/slirp.pc

about:
  home: https://gitlab.freedesktop.org/slirp/libslirp
  dev_url: https://gitlab.freedesktop.org/slirp/libslirp
  doc_url: https://gitlab.freedesktop.org/slirp/libslirp
  license: BSD-3-Clause
  license_file: COPYRIGHT
  summary: A general purpose TCP-IP emulator used by virtual machine hypervisors to provide virtual networking services. Adapted from mbargull's conda-forge recipe (which doesn't build on MacOS).
  description: >
    libslirp is a user-mode networking library used by virtual machines, containers or various tools.

